package org.example;

public enum Feature {
    // Java 1
    INNER_CLASS,
    // Java 2
    STRICTFP,
    SWITCH_STATEMENT,
    // Java 3
    // Java 4
    ASSERT,
    // Java 5
    ANNOTATION,
    ENUM,
    GENERIC_CLASS,
    GENERIC_METHOD,
    FOR_EACH,
    STATIC_IMPORT_DECLARATION,
    VARARGS,
    // Java 6
    // Java 7
    BINARY_BOOLEAN_LITERAL_EXPRESSION,
    BINARY_DOUBLE_LITERAL_EXPRESSION,
    BINARY_INTEGER_LITERAL_EXPRESSION,
    BINARY_LONG_LITERAL_EXPRESSION,
    CATCH_MULTIPLE_EXCEPTION_TYPES,
    DIAMOND_OPERATOR,
    STRING_SWITCH,
    TRY_WITH_RESOURCES,
    UNDERSCORE_IN_DOUBLE_LITERAL,
    UNDERSCORE_IN_INTEGER_LITERAL,
    UNDERSCORE_IN_LONG_LITERAL,
    // Java 8
    INTERFACE_DEFAULT_METHOD,
    INTERFACE_STATIC_METHOD,
    LAMBDA_EXPRESSION,
    METHOD_REFERENCE_EXPRESSION,
    OPTIONAL_VARIABLE_DECLARATION,
    REPEATABLE_ANNOTATION,
    TYPE_ANNOTATION,
    // Java 9
    INTERFACE_PRIVATE_METHOD,
    SAFE_VARARGS,
    TRY_WITH_RESOURCES_FINAL_VARIABLE,
    VARHANDLE,
    // Java 10
    VAR_TYPE,
    // Java 11
    LAMBDA_VAR_TYPE,
    // Java 12
    // Java 13
    // Java 14
    SWITCH_EXPRESSION, // Preview 12
    SWITCH_ENTRY_MULTIPLE_LABELS, // Preview 13
    SWITCH_ENTRY_TYPE_EXPRESSION, // Preview 13
    YIELD, // Preview 13
    // Java 15
    TEXT_BLOCK_LITERAL_EXPRESSION, // Preview 13
    TEXT_BLOCK_ESCAPE_NEWLINE, // Preview 14
    TEXT_BLOCK_ESCAPE_SPACE, // Preview 14
    // Java 16
    INSTANCE_OF_PATTERN, // Preview 14
    RECORD, // Preview 14
    LOCAL_RECORD, // Preview 15
    // Java 17
    SEALED_MODIFIER, // Preview 15
    // Java 18
    // Java 19
    // Java 20
    // Java 21
    FOR_EACH_RECORD_PATTERN_EXPRESSION, // Preview 20
    INSTANCEOF_RECORD_PATTERN_EXPRESSION, // Preview 19
    SWITCH_EXPRESSION_GUARD, // Preview 17 (or 19?)
    SWITCH_EXPRESSION_PATTERN_MATCHING, // Preview 17
    SWITCH_EXPRESSION_RECORD_PATTERN_EXPRESSION, // Preview 19
    SWITCH_STATEMENT_GUARD, // Preview 17 (or 19?)
    SWITCH_STATEMENT_PATTERN_MATCHING, // Preview 17
    SWITCH_STATEMENT_RECORD_PATTERN_EXPRESSION, // Preview 19
    // Java 22
    UNDERSCORE, // Preview 21
    // Java 23
    SWITCH_STATEMENT_PRIMITIVE_TYPE_PATTERN_EXPRESSION, // Preview
    SWITCH_EXPRESSION_PRIMITIVE_TYPE_PATTERN_EXPRESSION, // Preview
    INSTANCE_OF_PATTERN_PRIMITIVE_TYPE, // Preview
    // Java 24
    // Java 25
    UNNAMED_CLASS, // Preview 21
    FLEXIBLE_CONSTRUCTOR_BODIES, // Preview 22
    INSTANCE_MAIN_METHOD, // Preview 21
    MODULE_IMPORT_DECLARATION, // Preview 23
    NON_PUBLIC_MAIN_METHOD, // Preview 21
    STABLE_VALUE, // Preview
}
